/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javaapplication9.Ficha;
import javaapplication9.NewHibernateUtil;
import javaapplication9.Producto;
import org.hibernate.Session;

/**
 *
 * @author Facu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        this.initComponents();
        setLocationRelativeTo(null);//ubica en el medio
        setResizable(false);
        setTitle("EL REINO DE LA MIEL");
        panelCaja.setVisible(false);
        panelProductos.setVisible(false);
        panelPersonas.setVisible(false);
        panelRankings.setVisible(false);
        pestañaNuevoProd.setVisible(false);
        pestañaPersonas.setVisible(false);
        pestañaVerListado.setVisible(false);
        idProd=0;
    }
    public Image getIconImage(){
        Image getValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/iconoreino.png"));
        return getValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonProducto = new javax.swing.JButton();
        botonCaja = new javax.swing.JButton();
        botonPersonas = new javax.swing.JButton();
        botonRankings = new javax.swing.JButton();
        panelCaja = new javax.swing.JPanel();
        botonVenta = new javax.swing.JButton();
        botonConsignacion = new javax.swing.JButton();
        botonResumen = new javax.swing.JButton();
        botonDevolucion = new javax.swing.JButton();
        botonMovimientos = new javax.swing.JButton();
        panelProductos = new javax.swing.JPanel();
        botonVerListado = new javax.swing.JButton();
        botonNuevoProducto = new javax.swing.JButton();
        botonBorrarProducto = new javax.swing.JButton();
        botonStock = new javax.swing.JButton();
        panelPersonas = new javax.swing.JPanel();
        botonListado = new javax.swing.JButton();
        botonNuevaFicha = new javax.swing.JButton();
        botonModificarFicha = new javax.swing.JButton();
        botonBorrarFicha = new javax.swing.JButton();
        panelRankings = new javax.swing.JPanel();
        botonListado1 = new javax.swing.JButton();
        botonListado2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        pestañaPersonas = new javax.swing.JPanel();
        labelDNI = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelNuevaLider = new javax.swing.JLabel();
        labelNombrePersona = new javax.swing.JLabel();
        labelTipoPersona = new javax.swing.JLabel();
        botonGuardarPersona = new javax.swing.JButton();
        botonCancelarPersona = new javax.swing.JButton();
        ingresaDNI = new javax.swing.JTextField();
        ingresaNombrePersona = new javax.swing.JTextField();
        ingresaApellidoPersona = new javax.swing.JTextField();
        labelEstadoCivil = new javax.swing.JLabel();
        labelFechaNac = new javax.swing.JLabel();
        ingresaDomicilio = new javax.swing.JTextField();
        labelDomicilio = new javax.swing.JLabel();
        ingresaTelefono = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        jComboBoxEstCivil = new javax.swing.JComboBox<>();
        diaNacimiento = new javax.swing.JSpinner();
        mesNacimiento = new javax.swing.JSpinner();
        añoNacimiento = new javax.swing.JSpinner();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        ingresaLocalidad = new javax.swing.JTextField();
        labelLocalidad = new javax.swing.JLabel();
        labelFechaIngreso = new javax.swing.JLabel();
        diaIngreso = new javax.swing.JSpinner();
        mesIngreso = new javax.swing.JSpinner();
        añoIngreso = new javax.swing.JSpinner();
        ingresaCodPostal = new javax.swing.JTextField();
        labelCodPostal = new javax.swing.JLabel();
        pestañaNuevoProd = new javax.swing.JPanel();
        labelIdProd = new javax.swing.JLabel();
        LabelPrecio = new javax.swing.JLabel();
        LabelLinea = new javax.swing.JLabel();
        tituloNuevoProd = new javax.swing.JLabel();
        LabelNombreProd = new javax.swing.JLabel();
        botonGuardarNP = new javax.swing.JButton();
        botonCancelarNP = new javax.swing.JButton();
        ingresaCodProd = new javax.swing.JTextField();
        ingresaNombreProd = new javax.swing.JTextField();
        ingresaLinea = new javax.swing.JTextField();
        ingresaPrecio = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        labelNeto = new javax.swing.JLabel();
        ingresaCantidad = new javax.swing.JTextField();
        jComboBoxNeto = new javax.swing.JComboBox<>();
        pestañaVerListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tituloListadoProd = new javax.swing.JLabel();
        ingresaFiltroProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(766, 380));
        setMinimumSize(new java.awt.Dimension(766, 380));
        setPreferredSize(new java.awt.Dimension(766, 380));
        getContentPane().setLayout(null);

        botonProducto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        botonProducto.setText("PRODUCTOS");
        botonProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProductoMouseEntered(evt);
            }
        });
        botonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductoActionPerformed(evt);
            }
        });
        getContentPane().add(botonProducto);
        botonProducto.setBounds(190, 0, 190, 70);

        botonCaja.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        botonCaja.setText("CAJA");
        botonCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCajaMouseEntered(evt);
            }
        });
        botonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajaActionPerformed(evt);
            }
        });
        getContentPane().add(botonCaja);
        botonCaja.setBounds(0, 0, 190, 70);

        botonPersonas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        botonPersonas.setText("PERSONAS");
        botonPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPersonasMouseEntered(evt);
            }
        });
        botonPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(botonPersonas);
        botonPersonas.setBounds(380, 0, 190, 70);

        botonRankings.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        botonRankings.setText("RANKINGS");
        botonRankings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRankingsMouseEntered(evt);
            }
        });
        botonRankings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRankingsActionPerformed(evt);
            }
        });
        getContentPane().add(botonRankings);
        botonRankings.setBounds(570, 0, 190, 70);

        panelCaja.setLayout(null);

        botonVenta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonVenta.setText("VENTA");
        panelCaja.add(botonVenta);
        botonVenta.setBounds(0, 0, 190, 50);

        botonConsignacion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonConsignacion.setText("CONSIGNACION");
        panelCaja.add(botonConsignacion);
        botonConsignacion.setBounds(0, 50, 190, 50);

        botonResumen.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonResumen.setText("RESUMEN");
        panelCaja.add(botonResumen);
        botonResumen.setBounds(0, 200, 190, 50);

        botonDevolucion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonDevolucion.setText("DEVOLUCION");
        panelCaja.add(botonDevolucion);
        botonDevolucion.setBounds(0, 100, 190, 50);

        botonMovimientos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonMovimientos.setText("ULT. MOVIMIENTOS");
        panelCaja.add(botonMovimientos);
        botonMovimientos.setBounds(0, 150, 190, 50);

        getContentPane().add(panelCaja);
        panelCaja.setBounds(0, 70, 190, 250);

        panelProductos.setLayout(null);

        botonVerListado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonVerListado.setText("VER LISTADO");
        botonVerListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerListadoActionPerformed(evt);
            }
        });
        panelProductos.add(botonVerListado);
        botonVerListado.setBounds(0, 100, 190, 50);

        botonNuevoProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonNuevoProducto.setText("NUEVO PRODUCTO");
        botonNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoProductoActionPerformed(evt);
            }
        });
        panelProductos.add(botonNuevoProducto);
        botonNuevoProducto.setBounds(0, 0, 190, 50);

        botonBorrarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonBorrarProducto.setText("BORRAR PRODUCTO");
        panelProductos.add(botonBorrarProducto);
        botonBorrarProducto.setBounds(0, 50, 190, 50);

        botonStock.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonStock.setText("STOCK");
        panelProductos.add(botonStock);
        botonStock.setBounds(0, 150, 190, 50);

        getContentPane().add(panelProductos);
        panelProductos.setBounds(190, 70, 190, 200);

        panelPersonas.setLayout(null);

        botonListado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonListado.setText("LISTADO");
        panelPersonas.add(botonListado);
        botonListado.setBounds(0, 150, 190, 50);

        botonNuevaFicha.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonNuevaFicha.setText("NUEVA FICHA");
        botonNuevaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaFichaActionPerformed(evt);
            }
        });
        panelPersonas.add(botonNuevaFicha);
        botonNuevaFicha.setBounds(0, 0, 190, 50);

        botonModificarFicha.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonModificarFicha.setText("MODIFICAR FICHA");
        panelPersonas.add(botonModificarFicha);
        botonModificarFicha.setBounds(0, 50, 190, 50);

        botonBorrarFicha.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonBorrarFicha.setText("BORRAR FICHA");
        panelPersonas.add(botonBorrarFicha);
        botonBorrarFicha.setBounds(0, 100, 190, 50);

        getContentPane().add(panelPersonas);
        panelPersonas.setBounds(380, 70, 190, 200);

        panelRankings.setLayout(null);

        botonListado1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonListado1.setText("RANKING LIDERES");
        panelRankings.add(botonListado1);
        botonListado1.setBounds(0, 0, 190, 50);

        botonListado2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonListado2.setText("RANKING EXPERTAS");
        panelRankings.add(botonListado2);
        botonListado2.setBounds(0, 50, 190, 50);

        getContentPane().add(panelRankings);
        panelRankings.setBounds(570, 70, 190, 100);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reinofondo.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-10, 60, 780, 290);

        pestañaPersonas.setMaximumSize(new java.awt.Dimension(760, 280));
        pestañaPersonas.setPreferredSize(new java.awt.Dimension(760, 280));
        pestañaPersonas.setLayout(null);

        labelDNI.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelDNI.setText("DNI");
        pestañaPersonas.add(labelDNI);
        labelDNI.setBounds(20, 60, 100, 23);

        labelApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelApellido.setText("Apellido");
        pestañaPersonas.add(labelApellido);
        labelApellido.setBounds(20, 140, 70, 26);

        labelNuevaLider.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        labelNuevaLider.setText("AGREGAR NUEVA LIDER/EXPERTA");
        pestañaPersonas.add(labelNuevaLider);
        labelNuevaLider.setBounds(170, 10, 420, 30);

        labelNombrePersona.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelNombrePersona.setText("Nombre");
        pestañaPersonas.add(labelNombrePersona);
        labelNombrePersona.setBounds(20, 100, 90, 23);

        labelTipoPersona.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTipoPersona.setText("Tipo");
        pestañaPersonas.add(labelTipoPersona);
        labelTipoPersona.setBounds(20, 220, 50, 30);

        botonGuardarPersona.setText("Guardar");
        botonGuardarPersona.setEnabled(false);
        botonGuardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPersonaActionPerformed(evt);
            }
        });
        botonGuardarPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonGuardarPersonaKeyReleased(evt);
            }
        });
        pestañaPersonas.add(botonGuardarPersona);
        botonGuardarPersona.setBounds(600, 240, 133, 30);

        botonCancelarPersona.setText("Cancelar");
        botonCancelarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarPersonaActionPerformed(evt);
            }
        });
        pestañaPersonas.add(botonCancelarPersona);
        botonCancelarPersona.setBounds(450, 240, 133, 30);

        ingresaDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaDNIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaDNIKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaDNI);
        ingresaDNI.setBounds(120, 60, 140, 30);

        ingresaNombrePersona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaNombrePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaNombrePersonaActionPerformed(evt);
            }
        });
        ingresaNombrePersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaNombrePersonaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaNombrePersonaKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaNombrePersona);
        ingresaNombrePersona.setBounds(120, 100, 140, 30);

        ingresaApellidoPersona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaApellidoPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaApellidoPersonaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaApellidoPersonaKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaApellidoPersona);
        ingresaApellidoPersona.setBounds(120, 140, 140, 30);

        labelEstadoCivil.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelEstadoCivil.setText("Estado Civil");
        pestañaPersonas.add(labelEstadoCivil);
        labelEstadoCivil.setBounds(300, 180, 100, 26);

        labelFechaNac.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelFechaNac.setText("Fecha Nac.");
        pestañaPersonas.add(labelFechaNac);
        labelFechaNac.setBounds(20, 180, 100, 30);

        ingresaDomicilio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaDomicilioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaDomicilioKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaDomicilio);
        ingresaDomicilio.setBounds(410, 100, 130, 30);

        labelDomicilio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelDomicilio.setText("Domicilio");
        pestañaPersonas.add(labelDomicilio);
        labelDomicilio.setBounds(300, 100, 80, 30);

        ingresaTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaTelefonoKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaTelefono);
        ingresaTelefono.setBounds(410, 140, 130, 30);

        labelTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelTelefono.setText("Telefono");
        pestañaPersonas.add(labelTelefono);
        labelTelefono.setBounds(300, 140, 80, 30);

        jComboBoxEstCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casada", "Soltera" }));
        jComboBoxEstCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstCivilActionPerformed(evt);
            }
        });
        pestañaPersonas.add(jComboBoxEstCivil);
        jComboBoxEstCivil.setBounds(410, 180, 110, 30);

        diaNacimiento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        diaNacimiento.setMaximumSize(new java.awt.Dimension(39, 20));
        pestañaPersonas.add(diaNacimiento);
        diaNacimiento.setBounds(120, 180, 40, 30);

        mesNacimiento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        mesNacimiento.setMaximumSize(new java.awt.Dimension(39, 20));
        pestañaPersonas.add(mesNacimiento);
        mesNacimiento.setBounds(170, 180, 40, 30);

        añoNacimiento.setModel(new javax.swing.SpinnerNumberModel(1917, 1917, 2100, 1));
        añoNacimiento.setMaximumSize(new java.awt.Dimension(63, 20));
        pestañaPersonas.add(añoNacimiento);
        añoNacimiento.setBounds(220, 180, 60, 30);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lider", "Experta" }));
        pestañaPersonas.add(jComboBoxTipo);
        jComboBoxTipo.setBounds(120, 220, 140, 30);

        ingresaLocalidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaLocalidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaLocalidadKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaLocalidad);
        ingresaLocalidad.setBounds(410, 60, 130, 30);

        labelLocalidad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelLocalidad.setText("Localidad");
        pestañaPersonas.add(labelLocalidad);
        labelLocalidad.setBounds(300, 60, 80, 30);

        labelFechaIngreso.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelFechaIngreso.setText("Fecha Ingreso");
        pestañaPersonas.add(labelFechaIngreso);
        labelFechaIngreso.setBounds(600, 60, 130, 30);

        diaIngreso.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        diaIngreso.setMaximumSize(new java.awt.Dimension(39, 20));
        pestañaPersonas.add(diaIngreso);
        diaIngreso.setBounds(580, 100, 40, 30);

        mesIngreso.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        mesIngreso.setMaximumSize(new java.awt.Dimension(39, 20));
        pestañaPersonas.add(mesIngreso);
        mesIngreso.setBounds(630, 100, 40, 30);

        añoIngreso.setModel(new javax.swing.SpinnerNumberModel(1917, 1917, 2100, 1));
        añoIngreso.setMaximumSize(new java.awt.Dimension(63, 20));
        pestañaPersonas.add(añoIngreso);
        añoIngreso.setBounds(680, 100, 60, 30);

        ingresaCodPostal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaCodPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaCodPostalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaCodPostalKeyTyped(evt);
            }
        });
        pestañaPersonas.add(ingresaCodPostal);
        ingresaCodPostal.setBounds(600, 180, 130, 30);

        labelCodPostal.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelCodPostal.setText("Cod. Postal");
        pestañaPersonas.add(labelCodPostal);
        labelCodPostal.setBounds(620, 140, 90, 30);

        getContentPane().add(pestañaPersonas);
        pestañaPersonas.setBounds(0, 70, 760, 280);

        pestañaNuevoProd.setMaximumSize(new java.awt.Dimension(760, 280));
        pestañaNuevoProd.setPreferredSize(new java.awt.Dimension(760, 280));
        pestañaNuevoProd.setLayout(null);

        labelIdProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelIdProd.setText("Código");
        pestañaNuevoProd.add(labelIdProd);
        labelIdProd.setBounds(20, 60, 70, 23);

        LabelPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelPrecio.setText("Precio");
        pestañaNuevoProd.add(LabelPrecio);
        LabelPrecio.setBounds(20, 180, 60, 26);

        LabelLinea.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelLinea.setText("Linea");
        pestañaNuevoProd.add(LabelLinea);
        LabelLinea.setBounds(20, 140, 50, 26);

        tituloNuevoProd.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloNuevoProd.setText("AGREGAR NUEVO PRODUCTO");
        pestañaNuevoProd.add(tituloNuevoProd);
        tituloNuevoProd.setBounds(200, 10, 360, 30);

        LabelNombreProd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LabelNombreProd.setText("Nombre");
        pestañaNuevoProd.add(LabelNombreProd);
        LabelNombreProd.setBounds(20, 100, 80, 23);

        botonGuardarNP.setText("Guardar");
        botonGuardarNP.setEnabled(false);
        botonGuardarNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarNPActionPerformed(evt);
            }
        });
        botonGuardarNP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonGuardarNPKeyReleased(evt);
            }
        });
        pestañaNuevoProd.add(botonGuardarNP);
        botonGuardarNP.setBounds(370, 210, 133, 30);

        botonCancelarNP.setText("Cancelar");
        botonCancelarNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarNPActionPerformed(evt);
            }
        });
        pestañaNuevoProd.add(botonCancelarNP);
        botonCancelarNP.setBounds(520, 210, 133, 30);

        ingresaCodProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaCodProdKeyReleased(evt);
            }
        });
        pestañaNuevoProd.add(ingresaCodProd);
        ingresaCodProd.setBounds(110, 60, 200, 30);

        ingresaNombreProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaNombreProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaNombreProdActionPerformed(evt);
            }
        });
        ingresaNombreProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaNombreProdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaNombreProdKeyTyped(evt);
            }
        });
        pestañaNuevoProd.add(ingresaNombreProd);
        ingresaNombreProd.setBounds(110, 100, 200, 30);

        ingresaLinea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaLineaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaLineaKeyTyped(evt);
            }
        });
        pestañaNuevoProd.add(ingresaLinea);
        ingresaLinea.setBounds(110, 140, 200, 30);

        ingresaPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaPrecioKeyTyped(evt);
            }
        });
        pestañaNuevoProd.add(ingresaPrecio);
        ingresaPrecio.setBounds(110, 180, 200, 30);

        labelCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelCantidad.setText("Cantidad");
        pestañaNuevoProd.add(labelCantidad);
        labelCantidad.setBounds(20, 220, 90, 26);

        labelNeto.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        labelNeto.setText("Neto");
        pestañaNuevoProd.add(labelNeto);
        labelNeto.setBounds(470, 120, 50, 30);

        ingresaCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresaCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ingresaCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresaCantidadKeyTyped(evt);
            }
        });
        pestañaNuevoProd.add(ingresaCantidad);
        ingresaCantidad.setBounds(110, 220, 200, 30);

        jComboBoxNeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        pestañaNuevoProd.add(jComboBoxNeto);
        jComboBoxNeto.setBounds(530, 120, 50, 30);

        getContentPane().add(pestañaNuevoProd);
        pestañaNuevoProd.setBounds(0, 70, 760, 280);

        pestañaVerListado.setMaximumSize(new java.awt.Dimension(760, 280));
        pestañaVerListado.setPreferredSize(new java.awt.Dimension(760, 280));
        pestañaVerListado.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Linea", "Cantidad", "Precio Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pestañaVerListado.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 700, 190);

        tituloListadoProd.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloListadoProd.setText("LISTADO DE PRODUCTOS");
        pestañaVerListado.add(tituloListadoProd);
        tituloListadoProd.setBounds(220, 10, 360, 30);
        pestañaVerListado.add(ingresaFiltroProd);
        ingresaFiltroProd.setBounds(330, 40, 130, 30);

        jLabel1.setText("Buscar:");
        pestañaVerListado.add(jLabel1);
        jLabel1.setBounds(260, 40, 70, 30);

        getContentPane().add(pestañaVerListado);
        pestañaVerListado.setBounds(0, 70, 760, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean hayPestañasAbiertas(){
        if((panelCaja.isVisible())||(panelProductos.isVisible())||(panelPersonas.isVisible())||(panelRankings.isVisible()))
            return true;
        else
            return false;
    }
    
    private void cerrarPestañas(){
        panelCaja.setVisible(false);
        panelProductos.setVisible(false);
        panelPersonas.setVisible(false);
        panelRankings.setVisible(false);
    }
    
    private boolean camposProductoCompletos(){
        if ((ingresaLinea.getText().length()!=0)&&(ingresaNombreProd.getText().length()!=0)
            &&(ingresaPrecio.getText().length()!=0) &&(ingresaCodProd.getText().length()!=0)
            &&(ingresaCantidad.getText().length()!=0))
            return true;
        else 
            return false;
    }

    private boolean camposFichaCompletos(){
        if ((ingresaDNI.getText().length()!=0)&&(ingresaNombrePersona.getText().length()!=0)
            &&(ingresaApellidoPersona.getText().length()!=0) &&(ingresaLocalidad.getText().length()!=0)
            &&(ingresaDomicilio.getText().length()!=0)&&(ingresaTelefono.getText().length()!=0)
            &&(ingresaCodPostal.getText().length()!=0))
            return true;
        else 
            return false;
    }
    
    private void botonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductoActionPerformed
        if (!hayPestañasAbiertas()){
            panelProductos.setVisible(true);
        }
        else
            cerrarPestañas();
    }//GEN-LAST:event_botonProductoActionPerformed

    private void botonPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonasActionPerformed
        if (!hayPestañasAbiertas()){
            panelPersonas.setVisible(true);
        }
        else
            cerrarPestañas();
    }//GEN-LAST:event_botonPersonasActionPerformed

    private void botonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajaActionPerformed
        if (!hayPestañasAbiertas()){
            panelCaja.setVisible(true);
        }
        else
            cerrarPestañas();
    }//GEN-LAST:event_botonCajaActionPerformed

    private void botonRankingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRankingsActionPerformed
        if (!hayPestañasAbiertas()){
            panelRankings.setVisible(true);
        }
        else
            cerrarPestañas();     
    }//GEN-LAST:event_botonRankingsActionPerformed

    private void botonCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCajaMouseEntered
        if(hayPestañasAbiertas()){
            cerrarPestañas();
            panelCaja.setVisible(true);
        }
    }//GEN-LAST:event_botonCajaMouseEntered

    private void botonProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductoMouseEntered
        if(hayPestañasAbiertas()){
            cerrarPestañas();
            panelProductos.setVisible(true);
        }
    }//GEN-LAST:event_botonProductoMouseEntered

    private void botonPersonasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPersonasMouseEntered
        if(hayPestañasAbiertas()){        
            cerrarPestañas();
            panelPersonas.setVisible(true);
        }
    }//GEN-LAST:event_botonPersonasMouseEntered

    private void botonRankingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRankingsMouseEntered
        if(hayPestañasAbiertas()){
            cerrarPestañas();
            panelRankings.setVisible(true);
        }
    }//GEN-LAST:event_botonRankingsMouseEntered

    private void botonNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoProductoActionPerformed
       // nuevoProd np = new nuevoProd();
       panelProductos.setVisible(false);
       fondo.setVisible(false);
       pestañaNuevoProd.setVisible(true);
       ingresaCodProd.setText(String.valueOf(idProd));
    }//GEN-LAST:event_botonNuevoProductoActionPerformed

    private void botonGuardarNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarNPActionPerformed
        Session session = NewHibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        try{
            Producto p1 = new Producto();       
            p1.setCantidad(Integer.parseInt(ingresaCantidad.getText()));
            p1.setCodigoprod(BigDecimal.valueOf(Integer.parseInt(ingresaCodProd.getText())));
            if(jComboBoxNeto.getSelectedItem().equals("Si"))
                p1.setEsneto(true);
            else
                p1.setEsneto(false);
            p1.setLineaprod(ingresaLinea.getText());
            p1.setNombreprod(ingresaNombreProd.getText());
            p1.setPrecioventapublico(BigDecimal.valueOf(Double.valueOf(ingresaPrecio.getText())));
            session.save(p1);
            session.getTransaction().commit();
        }   catch(Exception e)  {
            System.err.println(e);
        }
        pestañaNuevoProd.setVisible(false);
        fondo.setVisible(true);
        ingresaCodProd.setText("");
        ingresaLinea.setText("");
        ingresaPrecio.setText("");
        ingresaNombreProd.setText("");
        ingresaCantidad.setText("");
        botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_botonGuardarNPActionPerformed

    private void botonCancelarNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarNPActionPerformed
        pestañaNuevoProd.setVisible(false);
        fondo.setVisible(true);
        ingresaLinea.setText("");
        ingresaPrecio.setText("");
        ingresaNombreProd.setText("");   botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_botonCancelarNPActionPerformed

    private void ingresaNombreProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaNombreProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaNombreProdActionPerformed

    private void botonGuardarNPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonGuardarNPKeyReleased
    }//GEN-LAST:event_botonGuardarNPKeyReleased

    private void ingresaPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaPrecioKeyReleased
        if(camposProductoCompletos())
            botonGuardarNP.setEnabled(true);
        else
            botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_ingresaPrecioKeyReleased

    private void ingresaLineaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaLineaKeyReleased
        if(camposProductoCompletos())
            botonGuardarNP.setEnabled(true);
        else
            botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_ingresaLineaKeyReleased

    private void ingresaNombreProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaNombreProdKeyReleased
        if(camposProductoCompletos())
            botonGuardarNP.setEnabled(true);
        else
            botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_ingresaNombreProdKeyReleased

    private void ingresaLineaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaLineaKeyTyped
        
    }//GEN-LAST:event_ingresaLineaKeyTyped

    private void ingresaNombreProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaNombreProdKeyTyped
        char car = evt.getKeyChar();
        if((car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE))
            evt.consume();
    }//GEN-LAST:event_ingresaNombreProdKeyTyped

    private void ingresaPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaPrecioKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')&&(car!='.'))
            evt.consume();
    }//GEN-LAST:event_ingresaPrecioKeyTyped

    private void botonGuardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPersonaActionPerformed
        Session session = NewHibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        try{
            Ficha f1 = new Ficha();    
            f1.setApellido(ingresaApellidoPersona.getText());
            f1.setCategoria(jComboBoxTipo.getSelectedItem().toString());
            f1.setCodigopostal(Integer.parseInt(ingresaCodPostal.getText()));
            f1.setDni(Integer.parseInt(ingresaDNI.getText()));
            f1.setDomicilio(ingresaDomicilio.getText());
            f1.setEstadocivil(jComboBoxEstCivil.getSelectedItem().toString());
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            //String fecha =""
            Date fechaAux1 = new Date();
            fechaAux1.setDate(Integer.parseInt(diaIngreso.getValue().toString()));
            fechaAux1.setMonth(Integer.parseInt(mesIngreso.getValue().toString())-1);
            fechaAux1.setYear(Integer.parseInt(añoIngreso.getValue().toString())-1900);
            f1.setFechaingreso(fechaAux1);
            Date fechaAux2 = new Date();
            fechaAux2.setDate(Integer.parseInt(diaNacimiento.getValue().toString()));
            fechaAux2.setMonth(Integer.parseInt(mesNacimiento.getValue().toString())-1);
            fechaAux2.setYear(Integer.parseInt(añoNacimiento.getValue().toString())-1900);
            f1.setFechanac(fechaAux2);
            f1.setLocalidad(ingresaLocalidad.getText());
            f1.setNombre(ingresaNombrePersona.getText());
            f1.setTelefono(BigDecimal.valueOf(Integer.parseInt(ingresaTelefono.getText())));
            session.save(f1);
            session.getTransaction().commit();
        }   catch(Exception e)  {
            System.err.println(e);
        }
        pestañaPersonas.setVisible(false);
        fondo.setVisible(true);
        ingresaDNI.setText("");
        ingresaNombrePersona.setText("");
        ingresaApellidoPersona.setText("");
        ingresaLocalidad.setText("");
        ingresaDomicilio.setText("");
        ingresaTelefono.setText("");
        ingresaCodPostal.setText("");
        botonGuardarPersona.setEnabled(false);         // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarPersonaActionPerformed

    private void botonGuardarPersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonGuardarPersonaKeyReleased
        // NO VA NADA
    }//GEN-LAST:event_botonGuardarPersonaKeyReleased

    private void botonCancelarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarPersonaActionPerformed
        pestañaPersonas.setVisible(false);
        fondo.setVisible(true);
        ingresaDNI.setText("");
        ingresaNombrePersona.setText("");
        ingresaApellidoPersona.setText("");
        ingresaLocalidad.setText("");
        ingresaCodPostal.setText("");
        ingresaDomicilio.setText("");
        ingresaTelefono.setText("");
        botonGuardarNP.setEnabled(false);            // TODO add your handling code here:
        
    }//GEN-LAST:event_botonCancelarPersonaActionPerformed

    private void ingresaNombrePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaNombrePersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaNombrePersonaActionPerformed

    private void ingresaNombrePersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaNombrePersonaKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);
    }//GEN-LAST:event_ingresaNombrePersonaKeyReleased

    private void ingresaNombrePersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaNombrePersonaKeyTyped
        char car = evt.getKeyChar();
        if((car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE))
            evt.consume();
    }//GEN-LAST:event_ingresaNombrePersonaKeyTyped

    private void ingresaApellidoPersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaApellidoPersonaKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);
    }//GEN-LAST:event_ingresaApellidoPersonaKeyReleased

    private void ingresaApellidoPersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaApellidoPersonaKeyTyped
        char car = evt.getKeyChar();
        if((car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE))
            evt.consume();
    }//GEN-LAST:event_ingresaApellidoPersonaKeyTyped

    private void ingresaDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaDomicilioKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaDomicilioKeyReleased

    private void ingresaDomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaDomicilioKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE) )
            evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaDomicilioKeyTyped

    private void ingresaTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaTelefonoKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaTelefonoKeyReleased

    private void ingresaTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaTelefonoKeyTyped
        char car = evt.getKeyChar();
        if(car<'0' || car>'9')
            evt.consume();
    }//GEN-LAST:event_ingresaTelefonoKeyTyped

    private void jComboBoxEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstCivilActionPerformed

    private void botonNuevaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaFichaActionPerformed
       panelPersonas.setVisible(false);
       fondo.setVisible(false);
       pestañaPersonas.setVisible(true);
    }//GEN-LAST:event_botonNuevaFichaActionPerformed

    private void ingresaDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaDNIKeyTyped
        char car = evt.getKeyChar();
        if(car<'0' || car>'9')
            evt.consume();
    }//GEN-LAST:event_ingresaDNIKeyTyped

    private void ingresaCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaCantidadKeyReleased
        if(camposProductoCompletos())
            botonGuardarNP.setEnabled(true);
        else
            botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_ingresaCantidadKeyReleased

    private void ingresaCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaCantidadKeyTyped
        char car = evt.getKeyChar();
        if(car<'0' || car>'9')
            evt.consume();
    }//GEN-LAST:event_ingresaCantidadKeyTyped

    private void ingresaLocalidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaLocalidadKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaLocalidadKeyReleased

    private void ingresaLocalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaLocalidadKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')&& (car<'A' || car>'Z') && (car!=(char)KeyEvent.VK_SPACE) )
            evt.consume();
    }//GEN-LAST:event_ingresaLocalidadKeyTyped

    private void ingresaCodPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaCodPostalKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaCodPostalKeyReleased

    private void ingresaCodPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaCodPostalKeyTyped
        char car = evt.getKeyChar();
        if(car<'0' || car>'9')
            evt.consume();
    }//GEN-LAST:event_ingresaCodPostalKeyTyped

    private void ingresaCodProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaCodProdKeyReleased
        if(camposProductoCompletos())
            botonGuardarNP.setEnabled(true);
        else
            botonGuardarNP.setEnabled(false);
    }//GEN-LAST:event_ingresaCodProdKeyReleased

    private void ingresaDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresaDNIKeyReleased
        if(camposFichaCompletos())
            botonGuardarPersona.setEnabled(true);
        else
            botonGuardarPersona.setEnabled(false);
    }//GEN-LAST:event_ingresaDNIKeyReleased

    private void botonVerListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerListadoActionPerformed
       panelProductos.setVisible(false);
       fondo.setVisible(false);
       pestañaVerListado.setVisible(true);// TODO add your handling code here:
       
    }//GEN-LAST:event_botonVerListadoActionPerformed

    private void filtrarProductos(String texto){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLinea;
    private javax.swing.JLabel LabelNombreProd;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JSpinner añoIngreso;
    private javax.swing.JSpinner añoNacimiento;
    private javax.swing.JButton botonBorrarFicha;
    private javax.swing.JButton botonBorrarProducto;
    private javax.swing.JButton botonCaja;
    private javax.swing.JButton botonCancelarNP;
    private javax.swing.JButton botonCancelarPersona;
    private javax.swing.JButton botonConsignacion;
    private javax.swing.JButton botonDevolucion;
    private javax.swing.JButton botonGuardarNP;
    private javax.swing.JButton botonGuardarPersona;
    private javax.swing.JButton botonListado;
    private javax.swing.JButton botonListado1;
    private javax.swing.JButton botonListado2;
    private javax.swing.JButton botonModificarFicha;
    private javax.swing.JButton botonMovimientos;
    private javax.swing.JButton botonNuevaFicha;
    private javax.swing.JButton botonNuevoProducto;
    private javax.swing.JButton botonPersonas;
    private javax.swing.JButton botonProducto;
    private javax.swing.JButton botonRankings;
    private javax.swing.JButton botonResumen;
    private javax.swing.JButton botonStock;
    private javax.swing.JButton botonVenta;
    private javax.swing.JButton botonVerListado;
    private javax.swing.JSpinner diaIngreso;
    private javax.swing.JSpinner diaNacimiento;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField ingresaApellidoPersona;
    private javax.swing.JTextField ingresaCantidad;
    private javax.swing.JTextField ingresaCodPostal;
    private javax.swing.JTextField ingresaCodProd;
    private javax.swing.JTextField ingresaDNI;
    private javax.swing.JTextField ingresaDomicilio;
    private javax.swing.JTextField ingresaFiltroProd;
    private javax.swing.JTextField ingresaLinea;
    private javax.swing.JTextField ingresaLocalidad;
    private javax.swing.JTextField ingresaNombrePersona;
    private javax.swing.JTextField ingresaNombreProd;
    private javax.swing.JTextField ingresaPrecio;
    private javax.swing.JTextField ingresaTelefono;
    private javax.swing.JComboBox<String> jComboBoxEstCivil;
    private javax.swing.JComboBox<String> jComboBoxNeto;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCodPostal;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEstadoCivil;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelFechaNac;
    private javax.swing.JLabel labelIdProd;
    private javax.swing.JLabel labelLocalidad;
    private javax.swing.JLabel labelNeto;
    private javax.swing.JLabel labelNombrePersona;
    private javax.swing.JLabel labelNuevaLider;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipoPersona;
    private javax.swing.JSpinner mesIngreso;
    private javax.swing.JSpinner mesNacimiento;
    private javax.swing.JPanel panelCaja;
    private javax.swing.JPanel panelPersonas;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelRankings;
    private javax.swing.JPanel pestañaNuevoProd;
    private javax.swing.JPanel pestañaPersonas;
    private javax.swing.JPanel pestañaVerListado;
    private javax.swing.JLabel tituloListadoProd;
    private javax.swing.JLabel tituloNuevoProd;
    // End of variables declaration//GEN-END:variables
    private int idProd;
}
