package javaapplication9;
// Generated 08/08/2017 17:40:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private VentaId id;
     private Date fecha;
     private short cantidad;

    public Venta() {
    }

    public Venta(VentaId id, Date fecha, short cantidad) {
       this.id = id;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public VentaId getId() {
        return this.id;
    }
    
    public void setId(VentaId id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(short cantidad) {
        this.cantidad = cantidad;
    }




}


