package javaapplication9;
// Generated 08/08/2017 17:40:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VentaId generated by hbm2java
 */
public class VentaId  implements java.io.Serializable {


     private BigDecimal codigoproducto;
     private long dni;

    public VentaId() {
    }

    public VentaId(BigDecimal codigoproducto, long dni) {
       this.codigoproducto = codigoproducto;
       this.dni = dni;
    }
   
    public BigDecimal getCodigoproducto() {
        return this.codigoproducto;
    }
    
    public void setCodigoproducto(BigDecimal codigoproducto) {
        this.codigoproducto = codigoproducto;
    }
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(long dni) {
        this.dni = dni;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaId) ) return false;
		 VentaId castOther = ( VentaId ) other; 
         
		 return ( (this.getCodigoproducto()==castOther.getCodigoproducto()) || ( this.getCodigoproducto()!=null && castOther.getCodigoproducto()!=null && this.getCodigoproducto().equals(castOther.getCodigoproducto()) ) )
 && (this.getDni()==castOther.getDni());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodigoproducto() == null ? 0 : this.getCodigoproducto().hashCode() );
         result = 37 * result + (int) this.getDni();
         return result;
   }   


}


